#!/usr/bin/env python2.7
from pr2_trainer_sim import *

problems = {'first_world':
            {'hands': {'left': [], 'right': []},
             'tables': {'white_table': ['blue_box']},
             'small_tables': {'orange_table': ['green_box']},
             'movables': {'blue_box': ['red_box'],
                          'red_box': ['yellow_box'],
                          'green_box': [], 'yellow_box': []}},
            'second_world':
            {'hands': {'left': [], 'right': []},
             'tables': {'big_platform': ['detergent', 'soda']},
             'small_tables': {'first_platform': ['package'],
                              'second_platform': []},
             'movables': {'detergent': [],
                          'soda': [],
                          'package': ['other_package'],
                          'other_package': []}},
            'third_world':
            {'hands': {'left': [], 'right': []},
             'tables': {'orange_table': ['hard_box', 'green_box']},
             'small_tables': {'purple_platform': ['package']},
             'movables': {'blue_box': ['red_box'],
                          'red_box': ['yellow_box'],
                          'green_box': [], 'yellow_box': [],
                          'hard_box': ['blue_box'], 'package': []}},
            'fourth_world':
            {'hands': {'left': [], 'right': []},
                'tables': {'table': ['soft_box'], 'table_two': [],
                           'table_three': []},
             'small_tables': {},
             'movables': {'blue_box': ['red_box'],
                          'red_box': ['yellow_box'],
                          'green_box': [], 'yellow_box': ['green_box'],
                          'soft_box': ['blue_box']}},
            'fifth_world':
            {'hands': {'left': [], 'right': []},
                'tables': {'platform': ['item']},
                'small_tables': {'high_shelf': ['red_box'], 'low_shelf': []},
             'movables': {'item': ['box'],
                          'red_box': ['can'],
                          'big_box': [], 'can': ['soft_box'],
                          'box': ['big_box'],
                          'soft_box': []}},
            'sixth_world':
            {'hands': {'left': [], 'right': []},
             'tables': {'big_platform': []},
             'small_tables': {'first_platform': ['package'],
                              'second_platform': ['soda']},
             'movables': {'magenta_box': [],
                          'soda': ['hard_package'],
                          'package': ['other_package'],
                          'other_package': ['magenta_box'],
                          'hard_package': []}},
            'seventh_world':
            {'hands': {'left': [], 'right': []},
             'tables': {'large_surface': []},
             'small_tables': {'top': ['green_package'],
                              'flat_thing': ['soda'],
                              'smooth_thing': ['small_item']},
             'movables': {'small_item': ['slippery_can'],
                          'slippery_can': ['hard_package'],
                          'mail': ['other_package'],
                          'green_package': ['mail'],
                          'other_package': [],
                          'hard_package': [],
                          'soda': []}},
            'eigth_world':
            {'hands': {'left': [], 'right': []},
             'tables': {'bed': ['detergent'],
                        'counter': []},
             'small_tables': {'chair': ['food'],
                              'desk': ['drink']},
             'movables': {'soap': [],
                          'detergent': ['spoon'],
                          'spoon': ['knife'],
                          'fork': [],
                          'knife': ['soap'],
                          'food': [],
                          'drink': ['fork']}},
            'ninth_world':
            {'hands': {'left': [], 'right': []},
             'tables': {'workbench': ['oil']},
             'small_tables': {'stool': ['tire']},
             'movables': {'wrench': [],
                          'oil': ['wrench'],
                          'tire': ['batery'],
                          'battery': ['gas'],
                          'gas': []}},

            }
communicator = SimplifiedIPSBHPNCommunicator(problems)
communicator.start()
